window.CANVAS_DATA = {
  "proyecto": "Solución Sellos",
  "equipo": "Vicente Venegas, Martin Hellwing, Pedro Halperin",
  "bloques": {
    "problema":          { "contenido": "1. Pérdida de tiempo operativa (más de 1 hora por consulta buscando en fuentes dispersas: PDFs, papel, historial e internet).\n2. Dependencia e interrupciones a los vendedores más experimentados para resolver dudas técnicas.\n3. Fuga de ventas por demora en identificar el repuesto equivalente a tiempo.", "estado": "listo" },
    "segmento":          { "contenido": "1. Usuario principal: Cotizadores y asesores técnicos del área comercial de fábricas de sellos mecánicos.\n2. Early adopter / Usuario secundario: Compradores de repuestos e-commerce que buscan la equivalencia por el modelo de su bomba.", "estado": "listo" },
    "propuesta_valor":   { "contenido": "Identificar la equivalencia técnica exacta de sellos mecánicos estándar en segundos, eliminando las búsquedas manuales y acelerando la respuesta al cliente.", "estado": "listo" },
    "solucion":          { "contenido": "1. Buscador unificado interactivo: Consulta rápida por marca y modelo de bomba (filtro principal), tipo de fluido (acotado a 3-4 opciones clave) y medidas para sellos estándar.\n2. Matcheo visual con abanico de equivalencias: Despliegue de todas las opciones compatibles disponibles (marcas, materiales y variantes) para que el cotizador elija la adecuada.\n3. Módulo autoservicio con derivación a ventas: Interfaz simplificada para clientes finales con botón directo de consulta al cotizador ante dudas.", "estado": "listo" },
    "canales":           { "contenido": "1. Canal interno: Plataforma web de uso diario en las computadoras del mostrador y área comercial de la fábrica.\n2. Canal externo: Portal web integrado en la tienda e-commerce y acceso directo por WhatsApp.\n3. Difusión y adopción: Recomendación directa en mostrador por el vendedor, enlaces en cotizaciones digitales y acceso vía QR en catálogo.", "estado": "listo" },
    "metricas":          { "contenido": "1. Tiempo de respuesta por consulta: Reducción del tiempo dedicado a buscar equivalencias (meta: pasar de >60 min a <5 min).\n2. Autonomía del cotizador: Porcentaje de consultas resueltas directamente con la plataforma sin recurrir a vendedores senior.\n3. Adopción en autoservicio: Cantidad de búsquedas iniciadas por clientes en el e-commerce y % de conversión a cotizaciones/ventas.", "estado": "listo" },
    "valor_capturado":   { "contenido": "1. Ahorro de horas operativas: Liberación estimada de 10 a 15 horas semanales por cotizador (30 a 45 horas/semana totales en la fábrica).\n2. Escalabilidad en e-commerce: Absorción de un mayor volumen de consultas en la web (resolviendo automáticamente las consultas estándar/sencillas) sin saturar al equipo ni aumentar costos de personal.", "estado": "listo" },
    "estructura_costos": { "contenido": "1. Carga y estructuración de datos: Tiempo/esfuerzo dedicado a digitalizar y ordenar la información de catálogos y PDFs en la base de datos.\n2. Infraestructura y hosting: Aplicación web liviana y base de datos cloud de bajo costo ($0 a $15 USD/mes en Vercel/Supabase).\n3. Mantenimiento: Tiempo operativo para agregar nuevos modelos o marcas.", "estado": "listo" },
    "ventaja_injusta":   { "contenido": "1. Acceso directo en el lugar de trabajo: Integrante del equipo empleado en la fábrica con acceso diario a cotizadores, vendedores experimentados y clientes para validación constante.\n2. Conocimiento de dominio y acervo técnico: Más de 30 años de trayectoria de la fábrica en el mercado y posesión de manuales/PDFs de equivalencias multimarca.", "estado": "listo" }
  }
};
